name: inktober_2024_clock
description: An interactive game for Inktober ["Clock"], 2024.
version: 1.0.0+1
repository: https://github.com/tytydraco/inktober_2024_clock
publish_to: 'none'

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: any

flutter:
  uses-material-design: true
